"""Closed vocabularies for Ask Anything v2.

Planner-facing enums describe proposals only. They never authorize retrieval,
calculation, scientific support, or a conclusion.
"""

from enum import StrEnum


class Answerability(StrEnum):
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    NOT_SUPPORTED = "NOT_SUPPORTED"
    CLARIFICATION_REQUIRED = "CLARIFICATION_REQUIRED"
    DATA_UNAVAILABLE = "DATA_UNAVAILABLE"


class AnswerMode(StrEnum):
    DETERMINISTIC = "deterministic"
    GROUNDED_AI = "grounded_ai"


class SynthesisStyle(StrEnum):
    CONCISE = "CONCISE"
    EXPLANATORY = "EXPLANATORY"
    COMPARATIVE = "COMPARATIVE"
    CONTEXTUAL = "CONTEXTUAL"


class SynthesisSectionKind(StrEnum):
    KEY_EVIDENCE = "KEY_EVIDENCE"
    CONTEXT = "CONTEXT"
    UNCERTAINTY = "UNCERTAINTY"


class ConversationRole(StrEnum):
    USER = "user"
    ASSISTANT = "assistant"


class EntityKind(StrEnum):
    QB = "qb"
    COACH = "coach"
    TEAM = "team"


class QuestionType(StrEnum):
    QB_HISTORY = "QB_HISTORY"
    QB_PROFILE = "QB_PROFILE"
    QB_PROJECTION = "QB_PROJECTION"
    COACH_HISTORY = "COACH_HISTORY"
    COACH_QB_CONTEXT = "COACH_QB_CONTEXT"
    QB_COACHING_CONTEXT = "QB_COACHING_CONTEXT"
    TEAM_SCHEME = "TEAM_SCHEME"
    PCAE_RESEARCH = "PCAE_RESEARCH"
    PLAYER_SCHEME_ALIGNMENT = "PLAYER_SCHEME_ALIGNMENT"
    COMPARISON = "COMPARISON"
    PLAYER_TEAM_SCENARIO = "PLAYER_TEAM_SCENARIO"
    CAREER_COUNTERFACTUAL = "CAREER_COUNTERFACTUAL"
    ROOKIE_PROJECTION = "ROOKIE_PROJECTION"
    COACH_EFFECT = "COACH_EFFECT"
    UNKNOWN = "UNKNOWN"


class AnalyticalTask(StrEnum):
    GET_QB_HISTORY = "GET_QB_HISTORY"
    GET_QB_PROFILE = "GET_QB_PROFILE"
    GET_QB_PROJECTION = "GET_QB_PROJECTION"
    GET_COACH_ASSIGNMENTS = "GET_COACH_ASSIGNMENTS"
    GET_COACH_QB_CONTEXT = "GET_COACH_QB_CONTEXT"
    GET_QB_COACHING_CONTEXT = "GET_QB_COACHING_CONTEXT"
    GET_TEAM_SCHEME = "GET_TEAM_SCHEME"
    GET_PLAYCALLER_PCAE = "GET_PLAYCALLER_PCAE"
    COMPARE_QB_MEASUREMENTS = "COMPARE_QB_MEASUREMENTS"
    COMPARE_TEAM_SCHEME = "COMPARE_TEAM_SCHEME"
    COMPARE_COACH_EVIDENCE = "COMPARE_COACH_EVIDENCE"
    DESCRIBE_PLAYER_SCHEME_ALIGNMENT = "DESCRIBE_PLAYER_SCHEME_ALIGNMENT"


class RequestedOutput(StrEnum):
    DIRECT_ANSWER = "DIRECT_ANSWER"
    EVIDENCE = "EVIDENCE"
    UNCERTAINTY = "UNCERTAINTY"
    LIMITATIONS = "LIMITATIONS"
    FOLLOW_UPS = "FOLLOW_UPS"


class ContextDependency(StrEnum):
    NONE = "NONE"
    PRIOR_ENTITY = "PRIOR_ENTITY"
    PRIOR_SEASON = "PRIOR_SEASON"
    PRIOR_QUESTION = "PRIOR_QUESTION"


class EvidenceKind(StrEnum):
    QB_HISTORY = "QB_HISTORY"
    QB_PROFILE = "QB_PROFILE"
    QB_PROJECTION = "QB_PROJECTION"
    COACH_ASSIGNMENT = "COACH_ASSIGNMENT"
    COACH_QB_CONTEXT = "COACH_QB_CONTEXT"
    TEAM_SCHEME = "TEAM_SCHEME"
    PCAE = "PCAE"
    PLAYER_SCHEME_ALIGNMENT = "PLAYER_SCHEME_ALIGNMENT"
    SUMMARY = "SUMMARY"
    CLARIFICATION = "CLARIFICATION"
    LIMITATION = "LIMITATION"


class ResolutionStatus(StrEnum):
    EXACT = "EXACT"
    AMBIGUOUS = "AMBIGUOUS"
    NOT_FOUND = "NOT_FOUND"


class FeatureCategory(StrEnum):
    USAGE = "USAGE"
    EFFICIENCY = "EFFICIENCY"
    CONTEXTUAL_EFFICIENCY = "CONTEXTUAL_EFFICIENCY"
    STATE = "STATE"
    UNCERTAINTY = "UNCERTAINTY"
    DESCRIPTIVE_PERFORMANCE = "DESCRIPTIVE_PERFORMANCE"


class ConclusionKind(StrEnum):
    HISTORICAL_FACT = "HISTORICAL_FACT"
    DESCRIPTIVE_COMPARISON = "DESCRIPTIVE_COMPARISON"
    VERIFIED_ROLE_ATTRIBUTION = "VERIFIED_ROLE_ATTRIBUTION"
    DEVELOPMENT_QUALITY = "DEVELOPMENT_QUALITY"
    PLAYER_SCHEME_DESCRIPTIVE_ALIGNMENT = "PLAYER_SCHEME_DESCRIPTIVE_ALIGNMENT"
    PREDICTIVE_FIT = "PREDICTIVE_FIT"
    CAUSAL = "CAUSAL"
    NUMERICAL_COMPARISON_WINNER = "NUMERICAL_COMPARISON_WINNER"


class PermissionDecision(StrEnum):
    ALLOWED = "ALLOWED"
    ALLOWED_WITH_LIMITATIONS = "ALLOWED_WITH_LIMITATIONS"
    DENIED = "DENIED"


class ReasonCode(StrEnum):
    IMPLEMENTATION_NOT_AVAILABLE_YET = "IMPLEMENTATION_NOT_AVAILABLE_YET"
    SUPPORTED_ANALYTICAL_TASK = "SUPPORTED_ANALYTICAL_TASK"
    ENTITY_AMBIGUOUS = "ENTITY_AMBIGUOUS"
    ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND"
    DATA_NOT_AVAILABLE = "DATA_NOT_AVAILABLE"
    C17_SCENARIO_NOT_SUPPORTED = "C17_SCENARIO_NOT_SUPPORTED"
    C18_COUNTERFACTUAL_NOT_IMPLEMENTED = "C18_COUNTERFACTUAL_NOT_IMPLEMENTED"
    C20_ROOKIE_MODEL_NOT_ESTIMABLE = "C20_ROOKIE_MODEL_NOT_ESTIMABLE"
    FORWARD_PAE_NOT_SUPPORTED = "FORWARD_PAE_NOT_SUPPORTED"
    DESTINATION_TEAM_PROJECTION_NOT_SUPPORTED = "DESTINATION_TEAM_PROJECTION_NOT_SUPPORTED"
    CAUSAL_CONCLUSION_NOT_PERMITTED = "CAUSAL_CONCLUSION_NOT_PERMITTED"
    DEVELOPMENT_CONCLUSION_NOT_PERMITTED = "DEVELOPMENT_CONCLUSION_NOT_PERMITTED"
    INSUFFICIENT_COMPARABLE_EVIDENCE = "INSUFFICIENT_COMPARABLE_EVIDENCE"
    BOUNDED_SCOPE = "BOUNDED_SCOPE"
    TASK_NOT_ALLOWED = "TASK_NOT_ALLOWED"
    ENTITY_UNRESOLVED = "ENTITY_UNRESOLVED"
    SEASON_UNSUPPORTED = "SEASON_UNSUPPORTED"
    SCIENTIFICALLY_UNSUPPORTED = "SCIENTIFICALLY_UNSUPPORTED"


class Reliability(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNAVAILABLE = "UNAVAILABLE"
