import type {
  ApiPage,
  Citation,
  CoachAssignment,
  CoachImpact,
  CoachProfile,
  NetworkEdge,
  QbPae,
  QbProfile,
  QbSeason,
  RelationshipExplorerResponse,
  Team,
  Versions,
} from "../api/contracts";

export const versions: Versions = {
  load_id: "test-load",
  schema_version: "checkpoint-7.2",
  loader_version: "serving-loader-v3",
  api_contract_version: "api-v1.2",
  historical_data_version: "c3-test",
  expected_data_version: "c5-test",
  expected_model_version: "expected-test",
  coach_data_version: "c6-test",
  coach_model_version: "coach-impact-test",
};

export const teams: Team[] = [
  {
    load_id: "test-load",
    team_id: "team_den",
    team_abbr: "DEN",
    team_name: "Denver Broncos",
    payload: {},
  },
  {
    load_id: "test-load",
    team_id: "team_hou",
    team_abbr: "HOU",
    team_name: "Houston Texans",
    payload: {},
  },
];

export const qbSeason: QbSeason = {
  load_id: "test-load",
  player_id: "qb-1",
  display_name: "Test Quarterback",
  team_id: "team_den",
  season: 2025,
  scope: "analysis",
  games: 17,
  starts: 17,
  dropbacks: 620,
  epa_per_dropback: 0.15,
  cpoe: 2.4,
  success_rate: 0.49,
  sack_rate: 0.05,
  qualifies_default: true,
  metric_version: "qb-dropback-v1",
  payload: { interception_rate: 0.02, touchdown_rate: 0.06 },
};

export const qbPae: QbPae = {
  load_id: "test-load",
  player_id: "qb-1",
  display_name: "Test Quarterback",
  team_id: "team_den",
  season: 2025,
  data_version: "c5-test",
  model_version: "expected-test",
  expected_epa_per_dropback: 0.08,
  actual_epa_per_dropback: 0.15,
  performance_above_expectation: 0.07,
  prediction_interval_low: -0.02,
  prediction_interval_high: 0.18,
  eligibility_status: "eligible",
  reliability: "high",
  is_out_of_sample: true,
  payload: { training_end_season: 2024 },
};

export const assignment: CoachAssignment = {
  load_id: "test-load",
  assignment_key: "den-2025-hc",
  coach_id: "coach-1",
  canonical_name: "Test Coach",
  team_id: "team_den",
  team_abbr: "DEN",
  team_name: "Denver Broncos",
  season: 2025,
  role: "head_coach",
  start_week: 1,
  end_week: 18,
  interval_basis: "observed_game_weeks",
  verification_status: "verified",
  confidence_level: "high",
  is_interim: false,
  is_shared: false,
  is_retained: true,
  notes: "Test-only fixture",
  payload: {},
};

export const networkAssignments: CoachAssignment[] = [
  {
    ...assignment,
    assignment_key: "hou-hc",
    coach_id: "coach-1",
    canonical_name: "Test Coach",
    team_id: "team_hou",
    team_abbr: "HOU",
    team_name: "Houston Texans",
    season: 2020,
    start_week: 1,
    end_week: 4,
    is_interim: true,
    is_retained: true,
  },
  {
    ...assignment,
    assignment_key: "hou-oc",
    coach_id: "coach-2",
    canonical_name: "Second Coach",
    team_id: "team_hou",
    team_abbr: "HOU",
    team_name: "Houston Texans",
    season: 2020,
    role: "play_caller",
    start_week: 4,
    end_week: 17,
    interval_basis: "dated_source_weeks",
    verification_status: "provisional",
    confidence_level: "medium",
    is_shared: true,
    is_interim: false,
    is_retained: false,
  },
];

export const coachImpact: CoachImpact = {
  load_id: "test-load",
  coach_id: "coach-1",
  canonical_name: "Test Coach",
  role: "head_coach",
  data_version: "c6-test",
  model_version: "coach-impact-test",
  estimated_effect: 0.01,
  confidence_low: -0.02,
  confidence_high: 0.03,
  bootstrap_replicates: 200,
  bootstrap_attempted_replicates: 200,
  bootstrap_interval_available: true,
  interval_estimand: "conditional_coach_appearance",
  identified_effect: false,
  identification_status: "exploratory_team_environment_confounding",
  rank_eligible: false,
  rank_exclusion_reason: "exploratory_team_environment_confounding",
  ranking_status: "suppressed_exploratory",
  preliminary_rank: null,
  verified_dropbacks: 620,
  qualifying_qb_seasons: 1,
  distinct_quarterbacks: 1,
  payload: {},
};

export const edge: NetworkEdge = {
  load_id: "test-load",
  source_assignment_key: "hou-hc",
  target_assignment_key: "hou-oc",
  source_coach_id: "coach-1",
  target_coach_id: "coach-2",
  team_id: "team_hou",
  season: 2020,
  source_role: "head_coach",
  target_role: "play_caller",
  source_verification_status: "verified",
  target_verification_status: "provisional",
  source_confidence_level: "high",
  target_confidence_level: "medium",
  source_start_week: 1,
  source_end_week: 4,
  target_start_week: 4,
  target_end_week: 17,
  overlap_start_week: 4,
  overlap_end_week: 4,
  source_is_shared: false,
  target_is_shared: true,
  source_is_provisional: false,
  target_is_provisional: true,
};

export const relationshipExplorer: RelationshipExplorerResponse = {
  query: {
    mode: "team_history",
    coach_id: null,
    player_id: null,
    team_id: "team_den",
    start_season: 2024,
    end_season: 2025,
    role: null,
    verification_status: null,
    include_provisional: true,
  },
  versions,
  semantics: {
    coach_assignment:
      "Source-backed coaching assignment for the stated team-season interval",
    qb_team_season:
      "Authoritative QB participation/performance for one team-season",
    coach_qb_context:
      "QB participated for this team-season while the coaching assignment existed within the same season",
    exact_weekly_overlap: false,
  },
  nodes: [
    {
      node_id: "coach:coach-1",
      node_type: "coach",
      coach_id: "coach-1",
      canonical_name: "Test Coach",
    },
    {
      node_id: "coach:coach-2",
      node_type: "coach",
      coach_id: "coach-2",
      canonical_name: "Second Coach",
    },
    {
      node_id: "qb:qb-1",
      node_type: "quarterback",
      player_id: "qb-1",
      display_name: "Test Quarterback",
    },
    {
      node_id: "qb:qb-2",
      node_type: "quarterback",
      player_id: "qb-2",
      display_name: "Reserve Quarterback",
    },
    {
      node_id: "team-season:team_den:2024",
      node_type: "team_season",
      team_id: "team_den",
      team_abbr: "DEN",
      team_name: "Denver Broncos",
      season: 2024,
    },
    {
      node_id: "team-season:team_den:2025",
      node_type: "team_season",
      team_id: "team_den",
      team_abbr: "DEN",
      team_name: "Denver Broncos",
      season: 2025,
    },
    {
      node_id: "team-season:team_hou:2025",
      node_type: "team_season",
      team_id: "team_hou",
      team_abbr: "HOU",
      team_name: "Houston Texans",
      season: 2025,
    },
  ],
  relationships: [
    {
      relationship_id: "den-2024-hc",
      relationship_type: "coach_assignment",
      source_node_id: "coach:coach-1",
      target_node_id: "team-season:team_den:2024",
      assignment_key: "den-2024-hc",
      coach_id: "coach-1",
      team_id: "team_den",
      season: 2024,
      role: "head_coach",
      start_week: 1,
      end_week: 9,
      interval_basis: "observed_game_weeks",
      verification_status: "verified",
      confidence_level: "high",
      is_shared: false,
      is_interim: false,
      is_retained: true,
      is_provisional: false,
      citations: [
        {
          source_url: "https://example.com/den",
          source_title: "Denver staff",
          source_type: "team_source",
          source_accessed_at: "2026-08-30",
          evidence_locator: "staff",
          evidence_note: "Fixture evidence",
        },
      ],
      publication_version: "test-load",
    },
    {
      relationship_id: "den-2024-hc-interim",
      relationship_type: "coach_assignment",
      source_node_id: "coach:coach-2",
      target_node_id: "team-season:team_den:2024",
      assignment_key: "den-2024-hc-interim",
      coach_id: "coach-2",
      team_id: "team_den",
      season: 2024,
      role: "head_coach",
      start_week: 10,
      end_week: 18,
      interval_basis: "observed_game_weeks",
      verification_status: "verified",
      confidence_level: "high",
      is_shared: false,
      is_interim: true,
      is_retained: false,
      is_provisional: false,
      citations: [
        {
          source_url: "https://example.com/interim",
          source_title: "Interim appointment",
          source_type: "league_source",
          source_accessed_at: "2026-08-30",
          evidence_locator: "announcement",
          evidence_note: "Fixture interim evidence",
        },
      ],
      publication_version: "test-load",
    },
    {
      relationship_id: "hou-2025-oc",
      relationship_type: "coach_assignment",
      source_node_id: "coach:coach-1",
      target_node_id: "team-season:team_hou:2025",
      assignment_key: "hou-2025-oc",
      coach_id: "coach-1",
      team_id: "team_hou",
      season: 2025,
      role: "offensive_coordinator",
      start_week: 1,
      end_week: 18,
      interval_basis: "season_designation",
      verification_status: "provisional",
      confidence_level: "medium",
      is_shared: true,
      is_interim: false,
      is_retained: false,
      is_provisional: true,
      citations: [],
      publication_version: "test-load",
    },
    {
      relationship_id: "qb-team-season:qb-1:team_den:2024",
      relationship_type: "qb_team_season",
      source_node_id: "qb:qb-1",
      target_node_id: "team-season:team_den:2024",
      player_id: "qb-1",
      team_id: "team_den",
      season: 2024,
      dropbacks: 410,
      actual_epa_per_dropback: 0.11,
      expected_epa_per_dropback: 0.07,
      performance_above_expectation: 0.04,
      qualifies_default: true,
      eligibility_status: "eligible",
      reliability: "high",
      is_out_of_sample: true,
      metric_version: "qb-dropback-v1",
      model_version: "expected-test",
      historical_data_version: "c3-test",
      expected_data_version: "c5-test",
      publication_version: "test-load",
    },
    {
      relationship_id: "qb-team-season:qb-1:team_den:2025",
      relationship_type: "qb_team_season",
      source_node_id: "qb:qb-1",
      target_node_id: "team-season:team_den:2025",
      player_id: "qb-1",
      team_id: "team_den",
      season: 2025,
      dropbacks: 220,
      actual_epa_per_dropback: 0.15,
      expected_epa_per_dropback: 0.08,
      performance_above_expectation: 0.07,
      qualifies_default: true,
      eligibility_status: "eligible",
      reliability: "medium",
      is_out_of_sample: true,
      metric_version: "qb-dropback-v1",
      model_version: "expected-test",
      historical_data_version: "c3-test",
      expected_data_version: "c5-test",
      publication_version: "test-load",
    },
    {
      relationship_id: "qb-team-season:qb-1:team_hou:2025",
      relationship_type: "qb_team_season",
      source_node_id: "qb:qb-1",
      target_node_id: "team-season:team_hou:2025",
      player_id: "qb-1",
      team_id: "team_hou",
      season: 2025,
      dropbacks: 80,
      actual_epa_per_dropback: -0.03,
      expected_epa_per_dropback: 0.02,
      performance_above_expectation: -0.05,
      qualifies_default: false,
      eligibility_status: "ineligible",
      reliability: "low",
      is_out_of_sample: true,
      metric_version: "qb-dropback-v1",
      model_version: "expected-test",
      historical_data_version: "c3-test",
      expected_data_version: "c5-test",
      publication_version: "test-load",
    },
    {
      relationship_id: "qb-team-season:qb-2:team_den:2025",
      relationship_type: "qb_team_season",
      source_node_id: "qb:qb-2",
      target_node_id: "team-season:team_den:2025",
      player_id: "qb-2",
      team_id: "team_den",
      season: 2025,
      dropbacks: 18,
      actual_epa_per_dropback: -0.12,
      expected_epa_per_dropback: null,
      performance_above_expectation: null,
      qualifies_default: false,
      eligibility_status: null,
      reliability: null,
      is_out_of_sample: null,
      metric_version: "qb-dropback-v1",
      model_version: null,
      historical_data_version: "c3-test",
      expected_data_version: null,
      publication_version: "test-load",
    },
  ],
  node_count: 7,
  relationship_count: 7,
  max_nodes: 1000,
  max_relationships: 2000,
};

export const citation: Citation = {
  load_id: "test-load",
  assignment_key: "den-2025-hc",
  source_url: "https://example.com/source",
  source_title: "Test source",
  source_type: "team_source",
  source_accessed_at: "2026-08-30",
  evidence_locator: "page 1",
  evidence_note: "Test evidence",
  coach_id: "coach-1",
  team_id: "team_den",
  season: 2025,
  role: "head_coach",
};

export const qbProfile: QbProfile = {
  player: {
    player_id: "qb-1",
    display_name: "Test Quarterback",
    position: "QB",
    payload: {},
  },
  seasons: [qbSeason],
};

export const coachProfile: CoachProfile = {
  coach: { coach_id: "coach-1", canonical_name: "Test Coach" },
  role_history: [assignment],
};

export function page<T>(items: T[], offset = 0, limit = 200): ApiPage<T> {
  return {
    items: items.slice(offset, offset + limit),
    total: items.length,
    limit,
    offset,
  };
}

export function installApiFixture(
  overrides: Partial<Record<string, unknown>> = {},
) {
  const fetchMock = vi.fn(async (input: RequestInfo | URL) => {
    const url = new URL(String(input), "http://app.test");
    const path = url.pathname.replace(/^\/api/, "");
    const offset = Number(url.searchParams.get("offset") ?? 0);
    const limit = Number(url.searchParams.get("limit") ?? 200);
    const responses: Record<string, unknown> = {
      "/versions": versions,
      "/teams": page(teams, offset, limit),
      "/assignments": page([assignment, ...networkAssignments], offset, limit),
      "/coaches": page(
        [
          {
            load_id: "test-load",
            coach_id: "coach-1",
            canonical_name: "Test Coach",
            role: "head_coach",
          },
          {
            load_id: "test-load",
            coach_id: "coach-2",
            canonical_name: "Second Coach",
            role: "head_coach",
          },
        ],
        offset,
        limit,
      ),
      "/qbs": page([qbSeason], offset, limit),
      "/qbs/qb-1": qbProfile,
      "/qbs/qb-1/pae": page([qbPae], offset, limit),
      "/coaches/coach-1": coachProfile,
      "/coach-impact": page([coachImpact], offset, limit),
      "/citations": page([citation], offset, limit),
      "/network/edges": page([edge], offset, limit),
      "/relationships/explorer": {
        ...relationshipExplorer,
        query: {
          ...relationshipExplorer.query,
          mode: url.searchParams.get("mode") ?? "team_history",
          coach_id: url.searchParams.get("coach_id"),
          player_id: url.searchParams.get("player_id"),
          team_id: url.searchParams.get("team_id"),
          start_season: Number(url.searchParams.get("start_season") ?? 2010),
          end_season: Number(url.searchParams.get("end_season") ?? 2025),
          verification_status: url.searchParams.get("verification_status"),
          include_provisional:
            url.searchParams.get("include_provisional") === "true",
        },
      },
      ...overrides,
    };
    const body = responses[path];
    if (body instanceof Error) {
      return new Response(JSON.stringify({ detail: body.message }), {
        status: 503,
        headers: { "Content-Type": "application/json" },
      });
    }
    if (body === undefined) {
      return new Response(JSON.stringify({ detail: "Not found" }), {
        status: 404,
      });
    }
    return new Response(JSON.stringify(body), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  });
  vi.stubGlobal("fetch", fetchMock);
  return fetchMock;
}
